import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  const baseUrl = "https://www.multica.ai";

  return {
    rules: [
      {
        userAgent: "*",
        allow: ["/", "/about", "/changelog", "/legal/"],
        disallow: [
          "/api/",
          "/ws",
          "/auth/",
          "/issues",
          "/board",
          "/inbox",
          "/agents",
          "/settings",
          "/my-issues",
          "/runtimes",
          "/skills",
          // Private hotlinks generated by /build-your-team — must never
          // be indexed. The page itself also sets robots noindex/nofollow
          // metadata; this is belt-and-braces for crawlers that ignore
          // meta but respect robots.txt.
          "/plan/",
        ],
      },
    ],
    sitemap: [`${baseUrl}/sitemap.xml`, `${baseUrl}/docs/sitemap.xml`],
  };
}
