import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { PlanPageContent } from "@/features/landing/components/plan-page-content";
import { getLeadByHash } from "@/lib/landing/team-planner/storage";

// Always read fresh from the DB. The page is a private hotlink — no
// caching layer should ever serve a stale copy, especially once Phase 2
// (editable plans) lands.
export const dynamic = "force-dynamic";
export const revalidate = 0;

interface PageProps {
  params: Promise<{ hash: string }>;
}

export async function generateMetadata({
  params,
}: PageProps): Promise<Metadata> {
  const { hash } = await params;
  // We don't surface project_summary in the title — the URL is private but
  // shoulder-surfers and link previewers (Slack, iMessage) can read it.
  return {
    title: "Your Agenthost Plan",
    description:
      "Private AI development plan generated by the Agenthost Planner.",
    robots: {
      index: false,
      follow: false,
      googleBot: { index: false, follow: false },
    },
    alternates: { canonical: `/plan/${hash}` },
    openGraph: {
      title: "Agenthost — your AI development plan",
      description: "A private link to your AI development plan.",
      // No image; we don't want previewers to leak the project summary.
    },
  };
}

export default async function PlanByHashPage({ params }: PageProps) {
  const { hash } = await params;
  const lead = await getLeadByHash(hash);
  if (!lead) {
    notFound();
  }
  return <PlanPageContent lead={lead} />;
}
